# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Regressions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Wiki Checkout
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/revarbat/BOSL2.wiki.git

    - name: Get OpenSCAD Appimage
      run: |
        cd $GITHUB_WORKSPACE
        wget https://files.openscad.org/snapshots/OpenSCAD-2021.01.03.ai6611-a980a3a-x86_64.AppImage
        sudo mv OpenSCAD-2021.01.03.*-x86_64.AppImage /usr/local/bin/openscad
        sudo chmod +x /usr/local/bin/openscad

    - name: Run Regression Tests
      run: |
        cd $GITHUB_WORKSPACE
        export OPENSCADPATH=$(dirname $GITHUB_WORKSPACE)
        ./scripts/run_tests.sh

  CheckDocs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Wiki Checkout
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/revarbat/BOSL2.wiki.git

    - name: Install Python pip
      run: sudo apt-get install python3-pip

    - name: Install Python dev
      run: sudo apt-get install python3-dev python3-setuptools

    - name: Install Pillow Dependencies
      run: sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev

    - name: Install Pillow
      run: sudo pip3 install Pillow

    - name: Install OpenSCAD
      run: |
        cd $GITHUB_WORKSPACE
        wget https://files.openscad.org/snapshots/OpenSCAD-2021.01.03.ai6611-a980a3a-x86_64.AppImage
        sudo mv OpenSCAD-2021.01.03.*-x86_64.AppImage /usr/local/bin/openscad
        sudo chmod +x /usr/local/bin/openscad

    - name: Generate Index
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/genindex.sh

    - name: Generating Docs
      run: |
        cd $GITHUB_WORKSPACE
        export OPENSCADPATH=$(dirname $GITHUB_WORKSPACE)
        ./scripts/make_all_docs.sh -t -i

